=== yerayrdgzz/sew/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.uniovi.es"
           targetNamespace="http://www.uniovi.es"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

	<xs:complexType name="coordinatesType">
		<xs:sequence>
			<xs:element ref="longitude"/>
			<xs:element ref="latitude"/>
			<xs:element ref="altitude"/>
		</xs:sequence>
	</xs:complexType>

	<!-- Tipos numéricos específicos -->
	<xs:simpleType name="lengthType">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0.0"/>
			<xs:maxInclusive value="250000.0"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="widthType">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0.0"/>
			<xs:maxInclusive value="25.0"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="altitudeType">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0.0"/>
			<xs:maxInclusive value="500.0"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="distanceType">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0.0"/>
			<xs:maxInclusive value="5000.0"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="longitudeType">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-180.0"/>
			<xs:maxInclusive value="180.0"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="latitudeType">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-90.0"/>
			<xs:maxInclusive value="90.0"/>
		</xs:restriction>
	</xs:simpleType>


	<xs:element name="circuit">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="length"/>
				<xs:element ref="width"/>
				<xs:element ref="date"/>
				<xs:element ref="hour"/>
				<xs:element ref="turns"/>
				<xs:element ref="locality"/>
				<xs:element ref="country"/>
				<xs:element ref="sponsor"/>
				<xs:element ref="references"/>
				<xs:element ref="images"/>
				<xs:element ref="videos"/>
				<xs:element ref="coordinates"/>
				<xs:element ref="sections"/>
				<xs:element ref="champion"/>
				<xs:element ref="classifieds"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>


	<xs:element name="name" type="xs:string"/>

	<xs:element name="length">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="lengthType">
					<xs:attribute name="units" type="xs:string" fixed="metros"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="width">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="widthType">
					<xs:attribute name="units" type="xs:string" fixed="metros"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="date" type="xs:date"/>
	<xs:element name="hour" type="xs:time"/>
	<xs:element name="turns" type="xs:integer"/>
	<xs:element name="locality" type="xs:string"/>
	<xs:element name="country" type="xs:string"/>
	<xs:element name="sponsor" type="xs:string"/>


	<xs:element name="references">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="reference" minOccurs="3" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="reference">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="alt" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>


	<xs:element name="images">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="image" minOccurs="1" maxOccurs="5"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="image" type="xs:string"/>

	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="video" minOccurs="1" maxOccurs="3"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="video">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="alt" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>


	<xs:element name="coordinates" type="coordinatesType"/>

	<xs:element name="longitude" type="longitudeType"/>
	<xs:element name="latitude" type="latitudeType"/>

	<xs:element name="altitude">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="altitudeType">
					<xs:attribute name="units" type="xs:string" fixed="metros"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>


	<xs:element name="sections">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="section" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="section">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distance"/>
				<xs:element ref="sector"/>
				<xs:element ref="coordinates"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="distance">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="distanceType">
					<xs:attribute name="units" type="xs:string" fixed="metros"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="sector">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="50"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>


	<xs:element name="champion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="duration"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="duration" type="xs:duration"/>

	<xs:element name="classifieds">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="classified" minOccurs="3" maxOccurs="3"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="classified">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="position" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== yerayrdgzz/sew/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuit
xmlns="http://www.uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.uniovi.es circuito.xsd"
>
    <name>MotorLand Aragón</name>
    <length units="metros">5300</length>
    <width units="metros">12</width>
    <date>2025-06-08</date>
    <hour>14:00:00</hour>
    <turns>23</turns>
    <locality>Alcañiz. Teruel</locality>
    <country>Spain</country>
    <sponsor>GoPro</sponsor>
    <references>
        <reference alt="Motorland Aragon">https://www.motorlandaragon.com/es</reference>
        <reference alt="Wikipedia: Motorland Aragon">https://es.wikipedia.org/wiki/MotorLand_Arag%C3%B3n</reference>
        <reference alt="La Invernal 2026: Motorland Aragón busca la causa benéfica para su iniciativa solidaria">https://soymotero.net/noticia/la-invernal-2026-motorland-aragon-informacion/</reference>
    </references>
    <images>
        <image>multimedia/panorama.jpeg</image>
        <image>multimedia/recta.jpg</image>
        <image>multimedia/curva.jpg</image>
    </images>
    <videos>
        <video alt="Vídeo de una carrera de motogp">multimedia/circuito.mp4</video>
    </videos>
    <coordinates>
        <longitude>-0.1978288</longitude>
        <latitude>41.0782888</latitude>
        <altitude units="metros">368.63</altitude>
    </coordinates>
     <sections>
        <section>
            <distance units="metros">0</distance>
            <sector>1</sector>
            <coordinates>
                <longitude>-0.1978288</longitude>
                <latitude>41.0782888</latitude>
                <altitude units="metros">368.63</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">252</distance>
            <sector>1</sector>
            <coordinates>
                <longitude> -0.2000895003778302</longitude>
                <latitude>41.07968336235442</latitude>
                <altitude units="metros">373</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">26</distance>
            <sector>1</sector>
            <coordinates>
                <longitude>-0.2003694039327841</longitude>
                <latitude>41.07974621561362</latitude>
                <altitude units="metros">373</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">155</distance>
            <sector>2</sector>
            <coordinates>
                <longitude>-0.2015968578230232</longitude>
                <latitude>41.07872517901811</latitude>
                <altitude units="metros">372</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">67</distance>
            <sector>2</sector>
            <coordinates>
                <longitude>-0.2019908754487099</longitude>
                <latitude>41.07861618087568</latitude>
                <altitude units="metros">374</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">181</distance>
            <sector>2</sector>
            <coordinates>
                <longitude>-0.2024416556946007</longitude>
                <latitude>41.07858251487299</latitude>
                <altitude units="metros">380</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">41</distance>
            <sector>3</sector>
            <coordinates>
                <longitude>-0.2044046406307298</longitude>
                <latitude>41.07909188102565</latitude>
                <altitude units="metros">382</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">38</distance>
            <sector>3</sector>
            <coordinates>
                <longitude>-0.2048136636946785</longitude>
                <latitude>41.07931745718076</latitude>
                <altitude units="metros">384</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">233</distance>
            <sector>3</sector>
            <coordinates>
                <longitude>-0.2049861705030565</longitude>
                <latitude>41.07963026081038</latitude>
                <altitude units="metros">397</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">47</distance>
            <sector>3</sector>
            <coordinates>
                <longitude>-0.2054676501649666</longitude>
                <latitude>41.08173234201702</latitude>
                <altitude units="metros">397</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">90</distance>
            <sector>3</sector>
            <coordinates>
                <longitude>-0.205774735289274</longitude>
                <latitude>41.08204948008022</latitude>
                <altitude units="metros">391</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">40</distance>
            <sector>4</sector>
            <coordinates>
                <longitude>-0.2066939638250354</longitude>
                <latitude>41.08256944101463</latitude>
                <altitude units="metros">394</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">10</distance>
            <sector>4</sector>
            <coordinates>
                <longitude>-0.2070591643297826</longitude>
                <latitude>41.08254671874548</latitude>
                <altitude units="metros">397</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">20</distance>
            <sector>4</sector>
            <coordinates>
                <longitude>-0.2072350413255297</longitude>
                <latitude>41.08240337414477</latitude>
                <altitude units="metros">397</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">140</distance>
            <sector>4</sector>
            <coordinates>
                <longitude>-0.2076184896281397</longitude>
                <latitude>41.08115934857558</latitude>
                <altitude units="metros">405</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">80</distance>
            <sector>4</sector>
            <coordinates>
                <longitude>-0.2082594223587886</longitude>
                <latitude>41.08056638103825</latitude>
                <altitude units="metros">405</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">50</distance>
            <sector>4</sector>
            <coordinates>
                <longitude>-0.208701295378263</longitude>
                <latitude>41.08032541174668</latitude>
                <altitude units="metros">407</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">50</distance>
            <sector>5</sector>
            <coordinates>
                <longitude>-0.2092067279698129</longitude>
                <latitude>41.08011414914778</latitude>
                <altitude units="metros">408</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">40</distance>
            <sector>5</sector>
            <coordinates>
                <longitude>-0.2097356433107378</longitude>
                <latitude>41.07994097938012</latitude>
                <altitude units="metros">407</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">80</distance>
            <sector>5</sector>
            <coordinates>
                <longitude>-0.2100619310846075</longitude>
                <latitude>41.08007498664976</latitude>
                <altitude units="metros">407</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">330</distance>
            <sector>5</sector>
            <coordinates>
                <longitude>-0.2107347545889382</longitude>
                <latitude>41.08299270195446</latitude>
                <altitude units="metros">399</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">30</distance>
            <sector>5</sector>
            <coordinates>
                <longitude>-0.2105422518603006</longitude>
                <latitude>41.08325185730011</latitude>
                <altitude units="metros">397</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">80</distance>
            <sector>5</sector>
            <coordinates>
                <longitude>-0.209922335480191</longitude>
                <latitude>41.08340990748056</latitude>
                <altitude units="metros">394</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">30</distance>
            <sector>5</sector>
            <coordinates>
                <longitude>-0.2098125403740947</longitude>
                <latitude>41.08362510241861</latitude>
                <altitude units="metros">391</altitude>
            </coordinates>
        </section>
        <section>
            <distance units="metros">40</distance>
            <sector>5</sector>
            <coordinates>
